coffeshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('users/', include('users.urls')),
    path('pedidos/', include('orders.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import MyOrderView, CreateOrderProductView, OrdersAPI

urlpatterns = [
    path('mi-orden',MyOrderView.as_view(), name="order"),
    path('agregarProducto',CreateOrderProductView.as_view(),name='addProduct'),
    path("api/",OrdersAPI.as_view(), name="order_api"),
]

products/urls.py
from django.urls import path
from .views import ProductFromView,GetProductsView,ProductListAPI

urlpatterns = [
    path('agregar/', ProductFromView.as_view(), name="add_product"),
    path("lista", GetProductsView.as_view(), name="get_products"),
    path("api/", ProductListAPI.as_view(), name="get_productsapi"),
] 
# if (settings.DEBUG):
#   urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView,LogoutView
from django.urls import path

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', LogoutView.as_view(),name="logout")
]

orders/models.py
from django.db import models
from products.models import Product
from django.contrib.auth.models import User

# Create your models here.
class Orders(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  isActive = models.BooleanField(default=True)
  orderDate =models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return f"order {self.id} by {self.user}"
  
class OrderProduct(models.Model):
  order = models.ForeignKey(Orders, on_delete=models.CASCADE)
  product = models.ForeignKey(Product, on_delete=models.PROTECT)
  quantity = models.IntegerField()

  def __str__(self):
    return f"{self.order} - {self.product}"
  
  def get_order_products(self):
        return OrderProduct.objects.filter(order=self)

products/models.py
from django.db import models


# Create your models here.
class Product(models.Model):
    name = models.TextField(max_length=200, verbose_name="nombre")
    description = models.TextField(max_length=300, verbose_name="descripcion")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="precio")
    available = models.BooleanField(default=True, verbose_name="disponible")
    photo = models.ImageField(upload_to="logos", null=True, blank=True,verbose_name="Foto")
    createdAt = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self) -> str:
        return self.name

users/models.py
from django.db import models

# Create your models here.

orders/forms.py
from django.forms import ModelForm
from .models import OrderProduct

class OrderProductForm(ModelForm):
  class Meta:
    model= OrderProduct
    fields = ['product']

products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.Form):
  name = forms.CharField(max_length=200, label="Nombre")
  description = forms.CharField(max_length=300, label="Descripcion")
  price =  forms.DecimalField(max_digits=10, decimal_places=2, label="Precio")
  available = forms.BooleanField(initial=True, label="Disponible", required=False)
  photo = forms.ImageField(label="Foto",required=False)

  def save(self):
    Product.objects.create(
      name=self.cleaned_data["name"],
      description=self.cleaned_data["description"],
      price=self.cleaned_data["price"],
      available=self.cleaned_data["available"],
      photo=self.cleaned_data["photo"],
    )

orders/views.py
from django.views.generic import DetailView,CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Orders,OrderProduct
from .forms import OrderProductForm
from django.urls import reverse_lazy
from rest_framework.views import(APIView)
from rest_framework.response import Response
from rest_framework import status
from .serializers import  OrdersSerializer

# Create your views here.
class MyOrderView(LoginRequiredMixin,DetailView):
  model =  Orders
  template_name ='orders/order.html'
  context_object_name ="order"

  def get_object(self):
    return Orders.objects.filter(isActive=True,user=self.request.user).first()
  
class CreateOrderProductView(LoginRequiredMixin,CreateView):
  template_name='orders/create_order_product.html'
  form_class = OrderProductForm
  success_url = reverse_lazy('order')

  def form_valid(self, form):
      order, _ = Orders.objects.get_or_create(
         isActive=True,
         user = self.request.user
      )
      form.instance.order = order
      form.instance.quantity = 1
      form.save()
      return super().form_valid( form)
  

class OrdersAPI(APIView):
    authentication_classes=[]
    permission_classes=[]
    def get(self,request):
      orders = Orders.objects.all()
      serializer = OrdersSerializer(orders,many=True)
      return Response(serializer.data)

    def post(self, request):
        serializer = OrdersSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

products/views.py
from django.urls import reverse_lazy
from django.views import generic
from .forms import ProductForm
from .serializers import ProductSerializer
from .models import Product
from rest_framework.views import(APIView)
from rest_framework.response import Response
from rest_framework import status

# Create your views here.
class ProductFromView(generic.FormView):
  template_name = 'products/add_product.html'

  form_class = ProductForm
  success_url = reverse_lazy('get_products')

  def form_valid(self, form):
      form.save()
      return super().form_valid(form)

class GetProductsView(generic.ListView):
  #  template_name = "products/get_products.html"

  #  def get_context_data (self):
  #     products_list = Product.objects.all()
  #     return {
  #     "products_list": products_list
  #   }
  model = Product
  template_name = 'products/get_products.html'
  context_object_name = 'products'

class ProductListAPI(APIView):
   authentication_classes=[]
   permission_classes=[]

   def get(self,request):
      products = Product.objects.all()
      serializer = ProductSerializer(products,many=True)
      return Response(serializer.data)
   
   def post(self, request):
        serializer = ProductSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.urls import reverse_lazy

# Create your views here.
class RegisterView(generic.GenericView):
  form_class = UserCreationForm
  template_name='users/register.html'
  success_url = reverse_lazy('login')

orders/templates/orders/order.html
{% extends "base.html" %} {% block content %} {{order.user.username}}
{{order.orderDate|date}}

<ul>
  {% for product_order in order.orderproduct_set.all %}
  {{product_order.product.name}} {{product_order.product.price}} {%empty%} No
  hay producto en la orden {% endfor %}
</ul>

{% endblock content %}

products/templates/products/add_product.html
<h1>Formulario</h1>
<form action="{% url "add_product" %}" method='post'>
  {% csrf_token %}

  {{form.as_p}}
  <button type="submit">Agregar</button>
</fom>

products/templates/products/get_products.html
{% extends "base.html" %} {% block content %}
<h1 class="text-3xl font-bold underline text-center py-4">Lista de carros</h1>
<ul class="flex gap-2 justify-center">
  {% for product in products %}
  <li class="w-64 h-72">
    <a href="#" class="group relative block overflow-hidden">
      <button
        class="absolute end-4 top-4 z-10 rounded-full bg-white p-1.5 text-gray-900 transition hover:text-gray-900/75"
      >
        <span class="sr-only">Wishlist</span>

        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke-width="1.5"
          stroke="currentColor"
          class="h-4 w-4"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z"
          />
        </svg>
      </button>
      {% if product.photo %}
      <img
        src="{{product.photo.url}}"
        alt="{{product.name}}"
        class="h-64 w-full object-cover transition duration-500 group-hover:scale-105 sm:h-72"
      />
      {% endif %}
      <div class="relative border border-gray-100 bg-white p-6">
        <span
          class="whitespace-nowrap bg-yellow-400 px-3 py-1.5 text-xs font-medium"
        >
          New
        </span>

        <h3 class="mt-4 text-lg font-medium text-gray-900">{{product.name}}</h3>

        <p class="mt-1.5 text-sm text-gray-700">${{product.price}}</p>

        <form action="{% url "addProduct" %}" class="mt-4" method="post">
          {% csrf_token %}
          <input type="hidden" name="product" value="{{product.id}}">

          <button
            class="block w-full rounded bg-yellow-400 p-4 text-sm font-medium transition hover:scale-105"
          >
            Agregar al pedido
          </button>
        </form>
      </div>
    </a>
  </li>
  {% endfor %}
</ul>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CoffeShop</title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <nav>
    {% if user.is_authenticated %}
    <h1>Hola, {{ user.username}}</h1>

    <form action="{% url "logout" %}" method='post'>
      {% csrf_token %}
      <button>Cerrar Cesion</button>
    </form>
    {% else %}
    <a href="{% url "login" %}" class=''>Login</a>
    {% endif %}
    <a href="#" class="inline-block rounded bg-indigo-600 px-8 py-3 text-sm font-medium text-white transition hover:scale-110 hover:shadow-xl focus:outline-none focus:ring active:bg-indigo-500">Mi Pedido</a>
  </nav>
    <div
      class="container mx-auto px-4 flex flex-col justify-center item-center"
    >
      {% block content %}{% endblock content %}
    </div>
  </body>
</html>

users/templates/users/login.html
{% extends "base.html" %} {% load tailwind_filters %} {% block content%}

<h1 class="p-6 text-center text-2xl font-bold">Iniciar Sesion</h1>
<form action="" class="w-64 border rounded p-3 mx-auto my-2" method="post">
  {% csrf_token %} {{form|crispy}}
  <button
    type="submit"
    class="inline-block rounded bg-indigo-600 px-8 py-3 text-sm font-medium text-white transition hover:scale-110 hover:shadow-xl focus:outline-none focus:ring active:bg-indigo-500"
  >
    Login
  </button>
</form>
{% endblock content%}